version: '2'
services:
  web:
    build: web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - POSTGRES_HOST=postgres://db/sicuro
    env_file: ./web/.env

  db:
    image: postgres

  nginx:
    build: nginx
    links:
      - web
    ports:
      - "80:80"
